#! /usr/bin/env python3


import argparse
from datetime import datetime
from pyzipei import ei_from_zipcode


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-z", "--zip", help="Provide US zipcode for which to recover utility information", default=27612)
    parser.add_argument("-v", "--verbose", help="Show verbose script output", action="store_true")
    parser.add_argument("-s", "--sector", help="Provide sector for which to recover rate, [Residential, Commercial, Industrial, or Transportation", default="Residential")
    args = parser.parse_args()

    if args.verbose:
        log = lambda x: print("{} | {}".format(datetime.utcnow(), x))
    else:
        log = lambda x: None

    print("{} rate for {}: {}".format(
        args.sector,
        args.zip,
        ei_from_zipcode(
            zipcode=args.zip,
            sector=args.sector,
            log=log
        )
    ))
